// Code generated by "stringer -type=BlockSelect,Register,ReadWrite,Size"; DO NOT EDIT.

package wiznet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CommonRegister-0]
	_ = x[Socket0Register-1]
	_ = x[Socket0TxBuffer-2]
	_ = x[Socket0RxBuffer-3]
	_ = x[Socket1Register-5]
	_ = x[Socket1TxBuffer-6]
	_ = x[Socket1RxBuffer-7]
	_ = x[Socket2Register-9]
	_ = x[Socket2TxBuffer-10]
	_ = x[Socket2RxBuffer-11]
	_ = x[Socket3Register-13]
	_ = x[Socket3TxBuffer-14]
	_ = x[Socket3RxBuffer-15]
	_ = x[Socket4Register-17]
	_ = x[Socket4TxBuffer-18]
	_ = x[Socket4RxBuffer-19]
	_ = x[Socket5Register-21]
	_ = x[Socket5TxBuffer-22]
	_ = x[Socket5RxBuffer-23]
	_ = x[Socket6Register-25]
	_ = x[Socket6TxBuffer-26]
	_ = x[Socket6RxBuffer-27]
	_ = x[Socket7Register-29]
	_ = x[Socket7TxBuffer-30]
	_ = x[Socket7RxBuffer-31]
}

const (
	_BlockSelect_name_0 = "CommonRegisterSocket0RegisterSocket0TxBufferSocket0RxBuffer"
	_BlockSelect_name_1 = "Socket1RegisterSocket1TxBufferSocket1RxBuffer"
	_BlockSelect_name_2 = "Socket2RegisterSocket2TxBufferSocket2RxBuffer"
	_BlockSelect_name_3 = "Socket3RegisterSocket3TxBufferSocket3RxBuffer"
	_BlockSelect_name_4 = "Socket4RegisterSocket4TxBufferSocket4RxBuffer"
	_BlockSelect_name_5 = "Socket5RegisterSocket5TxBufferSocket5RxBuffer"
	_BlockSelect_name_6 = "Socket6RegisterSocket6TxBufferSocket6RxBuffer"
	_BlockSelect_name_7 = "Socket7RegisterSocket7TxBufferSocket7RxBuffer"
)

var (
	_BlockSelect_index_0 = [...]uint8{0, 14, 29, 44, 59}
	_BlockSelect_index_1 = [...]uint8{0, 15, 30, 45}
	_BlockSelect_index_2 = [...]uint8{0, 15, 30, 45}
	_BlockSelect_index_3 = [...]uint8{0, 15, 30, 45}
	_BlockSelect_index_4 = [...]uint8{0, 15, 30, 45}
	_BlockSelect_index_5 = [...]uint8{0, 15, 30, 45}
	_BlockSelect_index_6 = [...]uint8{0, 15, 30, 45}
	_BlockSelect_index_7 = [...]uint8{0, 15, 30, 45}
)

func (i BlockSelect) String() string {
	switch {
	case i <= 3:
		return _BlockSelect_name_0[_BlockSelect_index_0[i]:_BlockSelect_index_0[i+1]]
	case 5 <= i && i <= 7:
		i -= 5
		return _BlockSelect_name_1[_BlockSelect_index_1[i]:_BlockSelect_index_1[i+1]]
	case 9 <= i && i <= 11:
		i -= 9
		return _BlockSelect_name_2[_BlockSelect_index_2[i]:_BlockSelect_index_2[i+1]]
	case 13 <= i && i <= 15:
		i -= 13
		return _BlockSelect_name_3[_BlockSelect_index_3[i]:_BlockSelect_index_3[i+1]]
	case 17 <= i && i <= 19:
		i -= 17
		return _BlockSelect_name_4[_BlockSelect_index_4[i]:_BlockSelect_index_4[i+1]]
	case 21 <= i && i <= 23:
		i -= 21
		return _BlockSelect_name_5[_BlockSelect_index_5[i]:_BlockSelect_index_5[i+1]]
	case 25 <= i && i <= 27:
		i -= 25
		return _BlockSelect_name_6[_BlockSelect_index_6[i]:_BlockSelect_index_6[i+1]]
	case 29 <= i && i <= 31:
		i -= 29
		return _BlockSelect_name_7[_BlockSelect_index_7[i]:_BlockSelect_index_7[i+1]]
	default:
		return "BlockSelect(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModeRegister-0]
	_ = x[GatewayIPAddressRegister-1]
	_ = x[SubnetMaskRegister-5]
	_ = x[HardwareAddressRegister-9]
	_ = x[IPAddressRegister-15]
	_ = x[InterruptLowLevelTimerRegister-19]
	_ = x[InterruptRegister-21]
	_ = x[InterruptMaskRegister-22]
	_ = x[SocketInterruptMaskRegister-24]
	_ = x[PHYConfigurationRegister-46]
	_ = x[VersionRegister-57]
	_ = x[SocketModeRegister-0]
	_ = x[SocketCommandRegister-1]
	_ = x[SocketInterruptRegister-2]
	_ = x[SocketStatusRegister-3]
	_ = x[SocketSourcePort-4]
	_ = x[SocketDestinationHardwareAddress-6]
	_ = x[SocketDestinationIPAddress-12]
	_ = x[SocketDestinationPort-16]
	_ = x[SocketMaximumSegmentSize-18]
	_ = x[SocketIPTOS-21]
	_ = x[SocketIPTTL-22]
	_ = x[SocketReceiveBufferSize-30]
	_ = x[SocketTransmitBufferSize-31]
	_ = x[SocketTransmitFreeSize-32]
	_ = x[SocketTransmitReadPointer-34]
	_ = x[SocketTransmitWritePointer-36]
	_ = x[SocketReceiveReceivedSize-38]
	_ = x[SocketReceiveReadPointer-40]
	_ = x[SocketReceiveWritePointer-42]
	_ = x[SocketInterruptMask-44]
	_ = x[SocketFragmentOffsetInIPHeader-45]
	_ = x[KeepaliveTimer-47]
}

const _Register_name = "ModeRegisterGatewayIPAddressRegisterSocketInterruptRegisterSocketStatusRegisterSocketSourcePortSubnetMaskRegisterSocketDestinationHardwareAddressHardwareAddressRegisterSocketDestinationIPAddressIPAddressRegisterSocketDestinationPortSocketMaximumSegmentSizeInterruptLowLevelTimerRegisterInterruptRegisterInterruptMaskRegisterSocketInterruptMaskRegisterSocketReceiveBufferSizeSocketTransmitBufferSizeSocketTransmitFreeSizeSocketTransmitReadPointerSocketTransmitWritePointerSocketReceiveReceivedSizeSocketReceiveReadPointerSocketReceiveWritePointerSocketInterruptMaskSocketFragmentOffsetInIPHeaderPHYConfigurationRegisterKeepaliveTimerVersionRegister"

var _Register_map = map[Register]string{
	0:  _Register_name[0:12],
	1:  _Register_name[12:36],
	2:  _Register_name[36:59],
	3:  _Register_name[59:79],
	4:  _Register_name[79:95],
	5:  _Register_name[95:113],
	6:  _Register_name[113:145],
	9:  _Register_name[145:168],
	12: _Register_name[168:194],
	15: _Register_name[194:211],
	16: _Register_name[211:232],
	18: _Register_name[232:256],
	19: _Register_name[256:286],
	21: _Register_name[286:303],
	22: _Register_name[303:324],
	24: _Register_name[324:351],
	30: _Register_name[351:374],
	31: _Register_name[374:398],
	32: _Register_name[398:420],
	34: _Register_name[420:445],
	36: _Register_name[445:471],
	38: _Register_name[471:496],
	40: _Register_name[496:520],
	42: _Register_name[520:545],
	44: _Register_name[545:564],
	45: _Register_name[564:594],
	46: _Register_name[594:618],
	47: _Register_name[618:632],
	57: _Register_name[632:647],
}

func (i Register) String() string {
	if str, ok := _Register_map[i]; ok {
		return str
	}
	return "Register(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReadAccessMode-0]
	_ = x[WriteAccessMode-4]
}

const (
	_ReadWrite_name_0 = "ReadAccessMode"
	_ReadWrite_name_1 = "WriteAccessMode"
)

func (i ReadWrite) String() string {
	switch {
	case i == 0:
		return _ReadWrite_name_0
	case i == 4:
		return _ReadWrite_name_1
	default:
		return "ReadWrite(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VariableLengthMode-0]
	_ = x[FixedLengthOneMode-1]
	_ = x[FixedLengthTwoMode-2]
	_ = x[FixedLengthFourMode-3]
}

const _Size_name = "VariableLengthModeFixedLengthOneModeFixedLengthTwoModeFixedLengthFourMode"

var _Size_index = [...]uint8{0, 18, 36, 54, 73}

func (i Size) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Size_index)-1 {
		return "Size(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Size_name[_Size_index[idx]:_Size_index[idx+1]]
}
